apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: movies-watchlist-ingress
  namespace: movies-watchlist
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
    - host: movies-watchlist.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: movies-watchlist-service
                port:
                  number: 80
