apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
  namespace: movies-watchlist
type: Opaque
data:


  # MongoDB root credentials
  mongo-root-username: cm9vdA==                    # root
  mongo-root-password: cm9vdHBhc3N3b3Jk            # rootpassword

  # MongoDB database and user
  mongo-database: bW92aWVzd2F0Y2hsaXN0            # movieswatchlist
  mongo-username: bW92aWVzdXNlcg==                # moviesuser
  mongo-password: bW92aWVzcGFzc3dvcmQ=            # moviespassword
---

